export interface Hexagram {
  number: number
  symbol: string
  nameHan: string
  nameVi: string
  upperTrigram: string
  lowerTrigram: string
  meaning: string
  advice: string
  energy: 'favorable' | 'neutral' | 'caution'
  keywords: string[]
}

export const HEXAGRAMS: Hexagram[] = [
  {
    number: 1, symbol: '䷀', nameHan: '乾', nameVi: 'Kiền',
    upperTrigram: 'Càn', lowerTrigram: 'Càn',
    meaning: 'Năng lượng thuần dương, sức mạnh sáng tạo đang ở đỉnh cao. Đây là thời điểm của hành động quyết đoán và lãnh đạo. Tiềm năng của bạn đang ở mức tối đa.',
    advice: 'Hành động với sự tự tin. Đây là lúc khởi sự những việc quan trọng.',
    energy: 'favorable', keywords: ['sáng tạo', 'lãnh đạo', 'sức mạnh', 'khởi đầu'],
  },
  {
    number: 2, symbol: '䷁', nameHan: '坤', nameVi: 'Khôn',
    upperTrigram: 'Khôn', lowerTrigram: 'Khôn',
    meaning: 'Sức mạnh của sự tiếp nhận và nuôi dưỡng. Không phải lúc dẫn đầu mà là lúc hỗ trợ và xây dựng nền tảng. Kiên nhẫn và bền bỉ là chìa khóa.',
    advice: 'Hãy tiếp nhận thay vì chủ động. Hỗ trợ người khác và củng cố nền tảng của mình.',
    energy: 'favorable', keywords: ['tiếp nhận', 'nuôi dưỡng', 'kiên nhẫn', 'nền tảng'],
  },
  {
    number: 3, symbol: '䷂', nameHan: '屯', nameVi: 'Truân',
    upperTrigram: 'Khảm', lowerTrigram: 'Chấn',
    meaning: 'Khó khăn ban đầu khi bắt đầu một điều mới. Như hạt giống đang cố thoát khỏi mặt đất — cần nỗ lực nhưng đang đi đúng hướng. Đây là giai đoạn hỗn độn có ích.',
    advice: 'Kiên trì qua giai đoạn khó khăn ban đầu. Tìm kiếm sự hỗ trợ từ người có kinh nghiệm.',
    energy: 'neutral', keywords: ['khó khăn', 'khởi đầu', 'kiên trì', 'hỗn độn'],
  },
  {
    number: 4, symbol: '䷃', nameHan: '蒙', nameVi: 'Mông',
    upperTrigram: 'Cấn', lowerTrigram: 'Khảm',
    meaning: 'Giai đoạn học hỏi và thiếu kinh nghiệm. Không phải xấu — đây là trạng thái ban đầu của mọi chuyên gia. Cởi mở và khiêm tốn là điều quan trọng nhất lúc này.',
    advice: 'Tìm thầy hoặc mentor. Đừng giả vờ biết khi chưa biết — sự thành thật về giới hạn bản thân là bước đầu tiên để vượt qua chúng.',
    energy: 'neutral', keywords: ['học hỏi', 'khiêm tốn', 'thiếu kinh nghiệm', 'mentor'],
  },
  {
    number: 5, symbol: '䷄', nameHan: '需', nameVi: 'Nhu',
    upperTrigram: 'Khảm', lowerTrigram: 'Càn',
    meaning: 'Thời điểm chờ đợi có chủ đích. Mây đã tụ nhưng mưa chưa rơi. Điều kiện chưa chín muồi — hành động vội vàng sẽ gây hại hơn lợi.',
    advice: 'Chuẩn bị trong khi chờ đợi. Duy trì sức mạnh và sự điềm tĩnh — cơ hội sẽ đến đúng thời điểm.',
    energy: 'neutral', keywords: ['chờ đợi', 'kiên nhẫn', 'chuẩn bị', 'thời điểm'],
  },
  {
    number: 6, symbol: '䷅', nameHan: '訟', nameVi: 'Tụng',
    upperTrigram: 'Càn', lowerTrigram: 'Khảm',
    meaning: 'Xung đột và tranh chấp đang nổi lên. Hai lực lượng đối lập không thể cùng tồn tại dễ dàng. Tiến hành đối đầu trực tiếp hiếm khi có lợi hoàn toàn.',
    advice: 'Giải quyết xung đột qua đối thoại trước khi leo thang. Nếu phải tranh chấp, tìm trọng tài trung lập.',
    energy: 'caution', keywords: ['xung đột', 'tranh chấp', 'đối thoại', 'thận trọng'],
  },
  {
    number: 7, symbol: '䷆', nameHan: '師', nameVi: 'Sư',
    upperTrigram: 'Khôn', lowerTrigram: 'Khảm',
    meaning: 'Cần tổ chức và kỷ luật để đạt mục tiêu lớn. Như một đội quân — sức mạnh không đến từ cá nhân mà từ sự phối hợp. Cần lãnh đạo rõ ràng và mục tiêu chung.',
    advice: 'Xây dựng đội nhóm và quy trình rõ ràng. Một mình khó có thể làm được việc lớn — hãy tin tưởng và phân công.',
    energy: 'neutral', keywords: ['tổ chức', 'kỷ luật', 'đội nhóm', 'lãnh đạo'],
  },
  {
    number: 8, symbol: '䷇', nameHan: '比', nameVi: 'Tỷ',
    upperTrigram: 'Khảm', lowerTrigram: 'Khôn',
    meaning: 'Thời điểm kết hợp và liên kết. Như nước thấm vào đất — mối quan hệ chân thực đang được xây dựng. Sự đoàn kết tự nguyện mang lại sức mạnh bền vững.',
    advice: 'Xây dựng liên minh và mối quan hệ tin cậy. Hãy chủ động kết nối trước khi bị cô lập.',
    energy: 'favorable', keywords: ['kết nối', 'liên minh', 'đoàn kết', 'quan hệ'],
  },
  {
    number: 9, symbol: '䷈', nameHan: '小畜', nameVi: 'Tiểu Súc',
    upperTrigram: 'Tốn', lowerTrigram: 'Càn',
    meaning: 'Kiềm chế nhỏ — năng lượng lớn bị kiềm chế bởi lực cản nhỏ. Chưa phải lúc bùng phát hoàn toàn. Tích lũy dần, củng cố từng bước nhỏ.',
    advice: 'Tập trung vào những cải thiện nhỏ thay vì thay đổi lớn. Sự kiên nhẫn tích lũy sẽ tạo đột phá sau này.',
    energy: 'neutral', keywords: ['tích lũy', 'kiềm chế', 'cải thiện nhỏ', 'bền vững'],
  },
  {
    number: 10, symbol: '䷉', nameHan: '履', nameVi: 'Lý',
    upperTrigram: 'Càn', lowerTrigram: 'Đoài',
    meaning: 'Đi trên con đường đúng đắn, dù có rủi ro. Như bước trên đuôi hổ — cần sự tập trung và cẩn trọng từng bước. Thái độ đúng quan trọng hơn kết quả tức thì.',
    advice: 'Hành động cẩn trọng và chính xác. Đừng để sự tự tin quá mức làm mờ đi sự cẩn thận cần thiết.',
    energy: 'neutral', keywords: ['cẩn trọng', 'đúng đắn', 'tập trung', 'thái độ'],
  },
  {
    number: 11, symbol: '䷊', nameHan: '泰', nameVi: 'Thái',
    upperTrigram: 'Khôn', lowerTrigram: 'Càn',
    meaning: 'Hòa bình và thịnh vượng. Âm dương hài hòa, mọi thứ đang chảy đúng hướng. Đây là giai đoạn thuận lợi hiếm có — trên dưới thông suốt, mọi thứ đều dễ dàng.',
    advice: 'Tận dụng giai đoạn thuận lợi để đặt nền móng vững chắc. Đừng lãng phí thời điểm tốt vào những việc phù phiếm.',
    energy: 'favorable', keywords: ['thịnh vượng', 'hòa bình', 'thuận lợi', 'hài hòa'],
  },
  {
    number: 12, symbol: '䷋', nameHan: '否', nameVi: 'Bĩ',
    upperTrigram: 'Càn', lowerTrigram: 'Khôn',
    meaning: 'Trì trệ và tắc nghẽn. Năng lượng không thể lưu thông — trên và dưới không kết nối được với nhau. Đây là giai đoạn khó khăn cần chấp nhận, không phủ nhận.',
    advice: 'Rút lui có chiến lược, không tiêu hao năng lực vào nơi không thể thay đổi. Giữ vững giá trị cốt lõi trong giai đoạn khó.',
    energy: 'caution', keywords: ['trì trệ', 'tắc nghẽn', 'rút lui', 'kiên định'],
  },
  {
    number: 13, symbol: '䷌', nameHan: '同人', nameVi: 'Đồng Nhân',
    upperTrigram: 'Càn', lowerTrigram: 'Ly',
    meaning: 'Cộng đồng và hợp tác trên tinh thần chung. Những người cùng lý tưởng tìm đến nhau. Sức mạnh đến từ sự liên kết có mục đích, không chỉ tiện lợi.',
    advice: 'Xây dựng cộng đồng xung quanh giá trị chung. Hãy thành thật về giá trị của bạn để thu hút đúng người.',
    energy: 'favorable', keywords: ['cộng đồng', 'hợp tác', 'lý tưởng', 'liên kết'],
  },
  {
    number: 14, symbol: '䷍', nameHan: '大有', nameVi: 'Đại Hữu',
    upperTrigram: 'Ly', lowerTrigram: 'Càn',
    meaning: 'Sở hữu lớn và thịnh vượng vượt bậc. Ánh sáng chiếu rọi từ trên cao, mọi thứ đều rõ ràng và dồi dào. Đây là đỉnh cao của sự thành công.',
    advice: 'Chia sẻ sự thịnh vượng với người xung quanh. Thành công bền vững đến từ việc nâng đỡ người khác, không chỉ giữ cho mình.',
    energy: 'favorable', keywords: ['thịnh vượng', 'thành công', 'dồi dào', 'chia sẻ'],
  },
  {
    number: 15, symbol: '䷎', nameHan: '謙', nameVi: 'Khiêm',
    upperTrigram: 'Khôn', lowerTrigram: 'Cấn',
    meaning: 'Sự khiêm tốn thực sự mang lại thành công lâu dài. Núi cao nhưng ẩn mình dưới đất — sức mạnh thực sự không cần phô trương. Người khiêm tốn được tôn trọng hơn kẻ kiêu ngạo.',
    advice: 'Hạ thấp cái tôi khi thành công, nâng cao người khác khi họ cần. Sự khiêm tốn chân thành là nền tảng của uy tín lâu dài.',
    energy: 'favorable', keywords: ['khiêm tốn', 'uy tín', 'lâu dài', 'thực chất'],
  },
  {
    number: 16, symbol: '䷏', nameHan: '豫', nameVi: 'Dự',
    upperTrigram: 'Chấn', lowerTrigram: 'Khôn',
    meaning: 'Nhiệt huyết và hứng khởi lan toa. Năng lượng tích cực có tính lây lan. Đây là lúc để truyền cảm hứng và chuẩn bị cho hành động lớn.',
    advice: 'Chia sẻ năng lượng tích cực của bạn. Sự hứng khởi chân thật có thể kéo người khác cùng tiến lên.',
    energy: 'favorable', keywords: ['nhiệt huyết', 'cảm hứng', 'năng lượng', 'chuyển động'],
  },
  {
    number: 17, symbol: '䷐', nameHan: '隨', nameVi: 'Tùy',
    upperTrigram: 'Đoài', lowerTrigram: 'Chấn',
    meaning: 'Thích nghi và theo dòng chảy. Không phải thụ động — mà là sự linh hoạt thông minh, biết khi nào nên dẫn và khi nào nên theo. Sự thích nghi là sức mạnh, không phải điểm yếu.',
    advice: 'Quan sát xu hướng và điều chỉnh theo. Đôi khi theo người khác là quyết định thông minh nhất bạn có thể đưa ra.',
    energy: 'favorable', keywords: ['thích nghi', 'linh hoạt', 'theo dòng', 'điều chỉnh'],
  },
  {
    number: 18, symbol: '䷑', nameHan: '蠱', nameVi: 'Cổ',
    upperTrigram: 'Cấn', lowerTrigram: 'Tốn',
    meaning: 'Sự hỏng hóc tích lũy từ lâu cần được xử lý. Như thức ăn hỏng trong hũ — vấn đề không tự biến mất mà ngày càng tệ hơn. Đã đến lúc dọn dẹp.',
    advice: 'Đối mặt với những vấn đề lâu nay bị bỏ qua. Sửa chữa dứt khoát hơn là tiếp tục né tránh.',
    energy: 'caution', keywords: ['sửa chữa', 'dọn dẹp', 'vấn đề lâu dài', 'đối mặt'],
  },
  {
    number: 19, symbol: '䷒', nameHan: '臨', nameVi: 'Lâm',
    upperTrigram: 'Khôn', lowerTrigram: 'Đoài',
    meaning: 'Sự tiếp cận và ảnh hưởng đang mở rộng. Cơ hội đang đến — hãy chuẩn bị tinh thần và tâm thế đúng. Người có quyền lực và tầm nhìn đang để ý đến bạn.',
    advice: 'Chuẩn bị cho cơ hội đang đến. Hành động chính trực ngay cả khi chưa ai nhìn — đó là khi tính cách thực sự được rèn giũa.',
    energy: 'favorable', keywords: ['cơ hội', 'tiếp cận', 'ảnh hưởng', 'chuẩn bị'],
  },
  {
    number: 20, symbol: '䷓', nameHan: '觀', nameVi: 'Quan',
    upperTrigram: 'Tốn', lowerTrigram: 'Khôn',
    meaning: 'Chiêm quan và quan sát. Nhìn rộng ra để hiểu bức tranh lớn trước khi hành động. Đây là lúc học hỏi từ môi trường xung quanh, không phải lúc áp đặt ý chí.',
    advice: 'Dừng lại và quan sát kỹ trước khi quyết định. Những gì bạn thấy từ vị trí trung lập thường chính xác hơn những gì bạn muốn thấy.',
    energy: 'neutral', keywords: ['quan sát', 'chiêm nghiệm', 'bức tranh lớn', 'học hỏi'],
  },
  {
    number: 21, symbol: '䷔', nameHan: '噬嗑', nameVi: 'Phệ Hạp',
    upperTrigram: 'Ly', lowerTrigram: 'Chấn',
    meaning: 'Cần cắt bỏ chướng ngại vật để tiến lên. Như cắn qua vật cứng — cần lực và quyết tâm nhưng kết quả xứng đáng. Không thể tiến lên nếu không xử lý trở ngại.',
    advice: 'Xử lý dứt khoát những trở ngại đang chặn đường bạn. Đừng để vấn đề nhỏ tích lũy thành rào cản lớn.',
    energy: 'neutral', keywords: ['xử lý', 'quyết đoán', 'trở ngại', 'dứt khoát'],
  },
  {
    number: 22, symbol: '䷕', nameHan: '賁', nameVi: 'Bí',
    upperTrigram: 'Cấn', lowerTrigram: 'Ly',
    meaning: 'Vẻ đẹp và hình thức bên ngoài. Trang trí và trình bày đẹp có giá trị — nhưng không thể thay thế cho nội dung thực chất. Hình thức và nội dung cần cân bằng.',
    advice: 'Chú ý đến cách trình bày nhưng đừng để nó che khuất bản chất. Đẹp mà rỗng thì chỉ ấn tượng nhất thời.',
    energy: 'neutral', keywords: ['hình thức', 'vẻ đẹp', 'cân bằng', 'trình bày'],
  },
  {
    number: 23, symbol: '䷖', nameHan: '剝', nameVi: 'Bác',
    upperTrigram: 'Cấn', lowerTrigram: 'Khôn',
    meaning: 'Sự xói mòn và tan rã. Cái cũ đang bị lột bỏ để nhường chỗ cho cái mới. Đây là giai đoạn kết thúc tự nhiên — không nên chống lại mà hãy để nó diễn ra.',
    advice: 'Chấp nhận những gì đang kết thúc. Buông bỏ điều không còn phù hợp là bước đầu tiên để tái sinh.',
    energy: 'caution', keywords: ['kết thúc', 'buông bỏ', 'xói mòn', 'chấp nhận'],
  },
  {
    number: 24, symbol: '䷗', nameHan: '復', nameVi: 'Phục',
    upperTrigram: 'Khôn', lowerTrigram: 'Chấn',
    meaning: 'Sự trở lại và tái sinh. Sau đêm dài nhất, ánh sáng bắt đầu quay trở lại. Một tia sáng nhỏ nhưng thực sự — đây là điểm khởi đầu của chu kỳ mới.',
    advice: 'Đây là thời điểm bắt đầu lại. Đừng vội vàng — hãy để quá trình phục hồi diễn ra tự nhiên từ gốc rễ.',
    energy: 'favorable', keywords: ['tái sinh', 'trở lại', 'khởi đầu mới', 'phục hồi'],
  },
  {
    number: 25, symbol: '䷘', nameHan: '無妄', nameVi: 'Vô Vọng',
    upperTrigram: 'Càn', lowerTrigram: 'Chấn',
    meaning: 'Hành động tự nhiên và không toan tính. Làm đúng vì đó là điều đúng, không vì kết quả. Khi hành động với sự chân thật thuần khiết, kết quả thường tốt một cách bất ngờ.',
    advice: 'Hành động theo trực giác và lương tâm, không chỉ theo tính toán. Sự chân thật mang lại may mắn bền vững hơn mưu mô.',
    energy: 'favorable', keywords: ['chân thật', 'tự nhiên', 'lương tâm', 'thuần khiết'],
  },
  {
    number: 26, symbol: '䷙', nameHan: '大畜', nameVi: 'Đại Súc',
    upperTrigram: 'Cấn', lowerTrigram: 'Càn',
    meaning: 'Tích lũy sức mạnh lớn. Năng lượng khổng lồ đang được giữ lại và tích tụ. Đây không phải sự yếu đuối mà là sự tích lũy thông minh cho thời điểm đúng.',
    advice: 'Tiếp tục học hỏi và tích lũy — đừng vội dùng hết sức mạnh đang tích tụ. Kỷ luật bây giờ tạo ra năng lực vượt trội sau này.',
    energy: 'favorable', keywords: ['tích lũy', 'kỷ luật', 'tiềm năng', 'chuẩn bị'],
  },
  {
    number: 27, symbol: '䷚', nameHan: '頤', nameVi: 'Di',
    upperTrigram: 'Cấn', lowerTrigram: 'Chấn',
    meaning: 'Nuôi dưỡng và chăm sóc — cả thể xác lẫn tinh thần. Những gì bạn ăn, đọc, và tiếp xúc hàng ngày sẽ định hình bạn. Hãy chọn lựa có ý thức những gì bạn nuôi dưỡng.',
    advice: 'Xem xét lại những gì bạn đang tiếp nhận — thức ăn, thông tin, quan hệ. Nuôi dưỡng đúng là nền tảng của mọi thứ.',
    energy: 'neutral', keywords: ['nuôi dưỡng', 'chăm sóc', 'lựa chọn', 'nền tảng'],
  },
  {
    number: 28, symbol: '䷛', nameHan: '大過', nameVi: 'Đại Quá',
    upperTrigram: 'Đoài', lowerTrigram: 'Tốn',
    meaning: 'Gánh nặng quá lớn so với khả năng chịu đựng. Như xà nhà bị uốn cong quá mức — cần gia cố hoặc giảm tải ngay. Tiếp tục như vậy sẽ dẫn đến đổ vỡ.',
    advice: 'Giảm tải ngay lập tức. Xác định điều gì đang vượt quá giới hạn và điều chỉnh trước khi quá muộn.',
    energy: 'caution', keywords: ['quá tải', 'giới hạn', 'giảm tải', 'cảnh báo'],
  },
  {
    number: 29, symbol: '䷜', nameHan: '坎', nameVi: 'Khảm',
    upperTrigram: 'Khảm', lowerTrigram: 'Khảm',
    meaning: 'Nguy hiểm liên tiếp, thử thách chồng chất. Như nước chảy qua hẻm núi — không thể dừng lại hay thoát ra bên cạnh, chỉ có thể tiến thẳng. Sự kiên định là chìa khóa duy nhất.',
    advice: 'Giữ vững tâm trí và tiến thẳng qua giai đoạn khó khăn. Đừng nhìn hai bên — tập trung vào con đường phía trước.',
    energy: 'caution', keywords: ['nguy hiểm', 'kiên định', 'thử thách', 'vượt qua'],
  },
  {
    number: 30, symbol: '䷝', nameHan: '離', nameVi: 'Ly',
    upperTrigram: 'Ly', lowerTrigram: 'Ly',
    meaning: 'Ánh sáng và sự rõ ràng. Lửa soi sáng mọi thứ nhưng cần bám vào nhiên liệu để duy trì. Sự rõ ràng trong tư duy và mục đích là sức mạnh lớn nhất bạn có.',
    advice: 'Làm rõ mục tiêu và ưu tiên của mình. Ánh sáng của sự hiểu biết sẽ lan toa — hãy chia sẻ cái nhìn rõ ràng của bạn.',
    energy: 'favorable', keywords: ['rõ ràng', 'ánh sáng', 'hiểu biết', 'mục đích'],
  },
  {
    number: 31, symbol: '䷞', nameHan: '咸', nameVi: 'Hàm',
    upperTrigram: 'Đoài', lowerTrigram: 'Cấn',
    meaning: 'Sự cảm ứng và thu hút lẫn nhau. Không phải ép buộc mà là sức hút tự nhiên — trái tim đến với trái tim. Mọi ảnh hưởng thực sự đều bắt đầu bằng sự kết nối chân thật.',
    advice: 'Mở lòng cho sự kết nối tự nhiên. Đừng ép buộc cảm xúc hay quan hệ — sự thu hút thực sự không cần nỗ lực quá mức.',
    energy: 'favorable', keywords: ['cảm ứng', 'thu hút', 'kết nối', 'tự nhiên'],
  },
  {
    number: 32, symbol: '䷟', nameHan: '恆', nameVi: 'Hằng',
    upperTrigram: 'Chấn', lowerTrigram: 'Tốn',
    meaning: 'Sự kiên trì và bền vững theo thời gian. Không phải cứng nhắc — mà là duy trì nhất quán trong khi vẫn thích nghi. Điều làm được đều đặn quan trọng hơn điều làm xuất sắc một lần.',
    advice: 'Xây dựng thói quen và quy trình bền vững thay vì cố gắng bùng phát ngắn hạn. Consistency beats intensity.',
    energy: 'favorable', keywords: ['kiên trì', 'nhất quán', 'thói quen', 'bền vững'],
  },
  {
    number: 33, symbol: '䷠', nameHan: '遯', nameVi: 'Độn',
    upperTrigram: 'Càn', lowerTrigram: 'Cấn',
    meaning: 'Rút lui chiến lược. Không phải bỏ cuộc — mà là nhận ra khi nào việc tiến lên không còn có lợi và lùi lại để bảo tồn sức mạnh. Rút lui đúng lúc là dấu hiệu của sự khôn ngoan.',
    advice: 'Đừng ngại rút lui khi môi trường không thuận lợi. Bảo tồn năng lực để chiến đấu vào ngày khác.',
    energy: 'neutral', keywords: ['rút lui', 'chiến lược', 'bảo tồn', 'khôn ngoan'],
  },
  {
    number: 34, symbol: '䷡', nameHan: '大壯', nameVi: 'Đại Tráng',
    upperTrigram: 'Chấn', lowerTrigram: 'Càn',
    meaning: 'Sức mạnh lớn đang ở đỉnh cao. Năng lượng mạnh mẽ — có thể tiến lên dễ dàng. Nhưng sức mạnh không kèm theo trí tuệ có thể dẫn đến sai lầm nghiêm trọng.',
    advice: 'Sử dụng sức mạnh đang có nhưng không lạm dụng. Quyền lực lớn nhất là biết khi nào nên dùng và khi nào nên giữ lại.',
    energy: 'favorable', keywords: ['sức mạnh', 'năng lượng', 'thận trọng', 'kiểm soát'],
  },
  {
    number: 35, symbol: '䷢', nameHan: '晉', nameVi: 'Tấn',
    upperTrigram: 'Ly', lowerTrigram: 'Khôn',
    meaning: 'Tiến bộ và thăng tiến rõ rệt. Như mặt trời mọc — sự tiến bộ diễn ra tự nhiên và rõ ràng. Đây là giai đoạn được công nhận và tiến lên.',
    advice: 'Tiếp tục tiến lên với sự tự tin. Đây là lúc năng lực của bạn được nhìn nhận — hãy tận dụng đà đang có.',
    energy: 'favorable', keywords: ['tiến bộ', 'thăng tiến', 'công nhận', 'phát triển'],
  },
  {
    number: 36, symbol: '䷣', nameHan: '明夷', nameVi: 'Minh Di',
    upperTrigram: 'Khôn', lowerTrigram: 'Ly',
    meaning: 'Ánh sáng bị che khuất. Tài năng và sự sáng suốt bị che lấp trong môi trường không thuận lợi. Đây là lúc cần giữ ánh sáng bên trong, không phô bày ra ngoài.',
    advice: 'Giữ kín tài năng và kế hoạch trong môi trường không an toàn. Bảo vệ ánh sáng bên trong để nó không bị dập tắt.',
    energy: 'caution', keywords: ['che giấu', 'bảo vệ', 'kiên nhẫn', 'môi trường khó'],
  },
  {
    number: 37, symbol: '䷤', nameHan: '家人', nameVi: 'Gia Nhân',
    upperTrigram: 'Tốn', lowerTrigram: 'Ly',
    meaning: 'Gia đình và cộng đồng thân thiết. Trật tự và vai trò rõ ràng trong nhóm nhỏ tạo ra nền tảng mạnh. Sự thay đổi xã hội bắt đầu từ việc xây dựng gia đình và cộng đồng gần nhất.',
    advice: 'Chú ý đến những mối quan hệ gần gũi nhất. Gia đình và nhóm thân thiết là nền tảng — hãy đầu tư vào đó.',
    energy: 'favorable', keywords: ['gia đình', 'cộng đồng', 'nền tảng', 'vai trò'],
  },
  {
    number: 38, symbol: '䷥', nameHan: '睽', nameVi: 'Khuê',
    upperTrigram: 'Ly', lowerTrigram: 'Đoài',
    meaning: 'Bất đồng và đối lập. Hai lực lượng nhìn theo hướng khác nhau. Nhưng ngay cả trong sự đối lập, vẫn có thể tìm ra điểm chung để cùng tiến.',
    advice: 'Tìm điểm chung trong bất đồng. Sự khác biệt không có nghĩa là xung đột — hãy tìm cách hợp tác dù khác quan điểm.',
    energy: 'caution', keywords: ['bất đồng', 'đối lập', 'điểm chung', 'hợp tác'],
  },
  {
    number: 39, symbol: '䷦', nameHan: '蹇', nameVi: 'Kiển',
    upperTrigram: 'Khảm', lowerTrigram: 'Cấn',
    meaning: 'Chướng ngại vật trên con đường phía trước. Tiến về phía trước gặp khó khăn — đây là lúc cần đánh giá lại hướng đi và tìm kiếm sự hỗ trợ.',
    advice: 'Đừng cố tiến lên một mình khi gặp chướng ngại lớn. Tìm kiếm người giúp đỡ và xem xét con đường thay thế.',
    energy: 'caution', keywords: ['chướng ngại', 'hỗ trợ', 'đánh giá lại', 'thay thế'],
  },
  {
    number: 40, symbol: '䷧', nameHan: '解', nameVi: 'Giải',
    upperTrigram: 'Chấn', lowerTrigram: 'Khảm',
    meaning: 'Giải phóng và tháo gỡ. Như tuyết tan sau mùa đông — căng thẳng và khó khăn đang được tháo gỡ. Đây là lúc thả lỏng và tiến về phía trước nhẹ nhàng hơn.',
    advice: 'Buông bỏ những oán giận và căng thẳng tích lũy. Tha thứ và tháo gỡ là hành động mạnh mẽ nhất bạn có thể làm lúc này.',
    energy: 'favorable', keywords: ['giải phóng', 'tháo gỡ', 'buông bỏ', 'nhẹ nhàng'],
  },
  {
    number: 41, symbol: '䷨', nameHan: '損', nameVi: 'Tổn',
    upperTrigram: 'Cấn', lowerTrigram: 'Đoài',
    meaning: 'Giảm bớt để được nhiều hơn. Đôi khi phải từ bỏ thứ có giá trị thấp để có được thứ có giá trị cao hơn. Sự đơn giản hóa có chủ đích là dạng tăng trưởng ngược.',
    advice: 'Xem xét những gì cần cắt giảm để tập trung vào điều thực sự quan trọng. Ít hơn nhưng tốt hơn.',
    energy: 'neutral', keywords: ['cắt giảm', 'đơn giản', 'tập trung', 'hy sinh'],
  },
  {
    number: 42, symbol: '䷩', nameHan: '益', nameVi: 'Ích',
    upperTrigram: 'Tốn', lowerTrigram: 'Chấn',
    meaning: 'Tăng trưởng và lợi ích. Đây là giai đoạn thuận lợi để mở rộng và đầu tư. Hành động tốt trong thời điểm này sẽ mang lại kết quả nhân lên nhiều lần.',
    advice: 'Hành động ngay trong giai đoạn thuận lợi này. Đầu tư vào bản thân, mối quan hệ, và mục tiêu dài hạn.',
    energy: 'favorable', keywords: ['tăng trưởng', 'lợi ích', 'đầu tư', 'mở rộng'],
  },
  {
    number: 43, symbol: '䷪', nameHan: '夬', nameVi: 'Quải',
    upperTrigram: 'Đoài', lowerTrigram: 'Càn',
    meaning: 'Đột phá và quyết định dứt khoát. Đã đến lúc nói ra sự thật và hành động rõ ràng. Tiếp tục né tránh sẽ chỉ làm vấn đề trầm trọng hơn.',
    advice: 'Nói thẳng và hành động quyết đoán. Công khai và minh bạch là chiến lược tốt nhất khi giải quyết vấn đề phức tạp.',
    energy: 'favorable', keywords: ['đột phá', 'quyết đoán', 'minh bạch', 'dứt khoát'],
  },
  {
    number: 44, symbol: '䷫', nameHan: '姤', nameVi: 'Cấu',
    upperTrigram: 'Càn', lowerTrigram: 'Tốn',
    meaning: 'Cuộc gặp gỡ bất ngờ và ảnh hưởng tinh tế. Một yếu tố mới xuất hiện — có thể là người, cơ hội, hoặc rủi ro. Cần nhận biết nhanh và đánh giá đúng bản chất của nó.',
    advice: 'Chú ý đến những điều mới xuất hiện trong cuộc sống. Không phải mọi cơ hội đều tốt — hãy đánh giá kỹ trước khi cam kết.',
    energy: 'neutral', keywords: ['gặp gỡ', 'bất ngờ', 'nhận biết', 'đánh giá'],
  },
  {
    number: 45, symbol: '䷬', nameHan: '萃', nameVi: 'Tụy',
    upperTrigram: 'Đoài', lowerTrigram: 'Khôn',
    meaning: 'Tập hợp và quy tụ. Mọi người và nguồn lực đang hội tụ về một mục tiêu chung. Đây là lúc tổ chức và định hướng cho năng lượng tập thể.',
    advice: 'Tổ chức và định hướng rõ ràng khi có nhiều người và nguồn lực cùng tập trung. Sức mạnh tập thể cần người lãnh đạo có tầm nhìn.',
    energy: 'favorable', keywords: ['tập hợp', 'quy tụ', 'tổ chức', 'tập thể'],
  },
  {
    number: 46, symbol: '䷭', nameHan: '升', nameVi: 'Thăng',
    upperTrigram: 'Khôn', lowerTrigram: 'Tốn',
    meaning: 'Vươn lên từ từ nhưng vững chắc. Không phải bước nhảy vọt mà là sự leo thang kiên nhẫn từng bước. Tiến bộ đều đặn sẽ đưa bạn đến nơi không tưởng.',
    advice: 'Tiếp tục tiến lên từng bước nhỏ. Đừng nản lòng vì tiến độ chậm — sự nhất quán tạo ra kết quả lớn.',
    energy: 'favorable', keywords: ['vươn lên', 'từng bước', 'kiên nhẫn', 'nhất quán'],
  },
  {
    number: 47, symbol: '䷮', nameHan: '困', nameVi: 'Khốn',
    upperTrigram: 'Đoài', lowerTrigram: 'Khảm',
    meaning: 'Kiệt sức và bế tắc. Nguồn lực cạn kiệt, đường ra không rõ ràng. Nhưng đây là thời điểm tính cách thực sự được kiểm tra — người mạnh vẫn giữ được phẩm giá.',
    advice: 'Giữ vững phẩm giá và giá trị khi ở điểm thấp nhất. Đây là giai đoạn thử lửa — và nó sẽ kết thúc.',
    energy: 'caution', keywords: ['kiệt sức', 'bế tắc', 'thử thách', 'phẩm giá'],
  },
  {
    number: 48, symbol: '䷯', nameHan: '井', nameVi: 'Tỉnh',
    upperTrigram: 'Khảm', lowerTrigram: 'Tốn',
    meaning: 'Nguồn lực bền vững và sâu sắc. Như giếng nước — luôn sẵn sàng cho mọi người, không cạn kiệt khi dùng đúng cách. Giá trị thực sự không mất đi khi chia sẻ.',
    advice: 'Đào sâu vào nguồn lực thực sự của mình. Chia sẻ kiến thức và kỹ năng — giá trị của bạn tăng lên khi được dùng, không giảm đi.',
    energy: 'favorable', keywords: ['nguồn lực', 'chia sẻ', 'bền vững', 'sâu sắc'],
  },
  {
    number: 49, symbol: '䷰', nameHan: '革', nameVi: 'Cách',
    upperTrigram: 'Đoài', lowerTrigram: 'Ly',
    meaning: 'Cách mạng và thay đổi căn bản. Không phải cải tiến nhỏ mà là sự biến đổi hoàn toàn. Thay đổi lớn cần thời điểm đúng và sự chuẩn bị kỹ lưỡng.',
    advice: 'Nếu đã đến lúc thay đổi căn bản, hãy làm dứt khoát. Thay đổi nửa vời thường tệ hơn không thay đổi.',
    energy: 'neutral', keywords: ['cách mạng', 'thay đổi', 'biến đổi', 'dứt khoát'],
  },
  {
    number: 50, symbol: '䷱', nameHan: '鼎', nameVi: 'Đỉnh',
    upperTrigram: 'Ly', lowerTrigram: 'Tốn',
    meaning: 'Sự nuôi dưỡng và chuyển hóa. Như nồi ấm biến nguyên liệu thô thành thức ăn — tài năng và nguồn lực thô cần được "nấu chín" qua quá trình và kỷ luật.',
    advice: 'Đầu tư vào quá trình phát triển, không chỉ kết quả. Sự chuyển hóa thực sự cần thời gian và nhiệt.',
    energy: 'favorable', keywords: ['chuyển hóa', 'phát triển', 'quá trình', 'kỷ luật'],
  },
  {
    number: 51, symbol: '䷲', nameHan: '震', nameVi: 'Chấn',
    upperTrigram: 'Chấn', lowerTrigram: 'Chấn',
    meaning: 'Cú sốc và đánh thức. Sấm sét đột ngột làm mọi thứ rõ ràng — đây là lúc tỉnh thức, dù có hơi đáng sợ. Sau cú sốc, người thức tỉnh sẽ nhìn thấy mọi thứ rõ ràng hơn.',
    advice: 'Đừng sợ những bất ngờ làm bạn tỉnh thức. Cú sốc đôi khi là món quà — nó buộc bạn phải đối mặt với thực tế.',
    energy: 'neutral', keywords: ['bất ngờ', 'tỉnh thức', 'đánh thức', 'rõ ràng'],
  },
  {
    number: 52, symbol: '䷳', nameHan: '艮', nameVi: 'Cấn',
    upperTrigram: 'Cấn', lowerTrigram: 'Cấn',
    meaning: 'Dừng lại và giữ yên. Biết khi nào cần dừng lại là kỹ năng quan trọng không kém biết khi nào cần tiến. Sự tĩnh lặng cho phép bạn quan sát và lấy lại sức.',
    advice: 'Dừng lại và nghỉ ngơi khi cần. Thiền định, tĩnh lặng, và phản chiếu nội tâm là hành động tích cực, không phải lãng phí thời gian.',
    energy: 'neutral', keywords: ['dừng lại', 'tĩnh lặng', 'nghỉ ngơi', 'thiền định'],
  },
  {
    number: 53, symbol: '䷴', nameHan: '漸', nameVi: 'Tiệm',
    upperTrigram: 'Tốn', lowerTrigram: 'Cấn',
    meaning: 'Tiến bộ từ từ và tự nhiên. Như con chim di cư — từng bước có mục đích, không vội vàng. Sự phát triển bền vững không thể bị ép buộc hay bỏ qua các bước.',
    advice: 'Theo đúng trình tự và tiến độ tự nhiên. Đừng đốt cháy giai đoạn — mỗi bước đều cần thiết cho sự phát triển vững chắc.',
    energy: 'favorable', keywords: ['từ từ', 'tự nhiên', 'trình tự', 'bền vững'],
  },
  {
    number: 54, symbol: '䷵', nameHan: '歸妹', nameVi: 'Quy Muội',
    upperTrigram: 'Chấn', lowerTrigram: 'Đoài',
    meaning: 'Mối quan hệ không hoàn toàn như mong muốn. Đang ở vị trí phụ hoặc không đúng vai trò. Chấp nhận hoàn cảnh và tìm cách đóng góp trong vị trí hiện tại.',
    advice: 'Làm tốt vai trò hiện tại dù nó không phải lý tưởng. Sự chuyên nghiệp trong mọi hoàn cảnh mở ra cơ hội tốt hơn.',
    energy: 'caution', keywords: ['vai trò', 'chấp nhận', 'chuyên nghiệp', 'hoàn cảnh'],
  },
  {
    number: 55, symbol: '䷶', nameHan: '豐', nameVi: 'Phong',
    upperTrigram: 'Chấn', lowerTrigram: 'Ly',
    meaning: 'Sự dồi dào và đỉnh cao. Ánh sáng và sức mạnh đều ở mức tối đa — nhưng đỉnh cao cũng là điểm bắt đầu của sự giảm sút nếu không biết cách duy trì.',
    advice: 'Tận hưởng và trân trọng giai đoạn dồi dào, nhưng đừng lãng phí. Đây là lúc tốt để củng cố và chuẩn bị cho chu kỳ tiếp theo.',
    energy: 'favorable', keywords: ['dồi dào', 'đỉnh cao', 'trân trọng', 'chuẩn bị'],
  },
  {
    number: 56, symbol: '䷷', nameHan: '旅', nameVi: 'Lữ',
    upperTrigram: 'Ly', lowerTrigram: 'Cấn',
    meaning: 'Hành trình và sự xa lạ. Đang ở vị trí không quen thuộc — như khách lữ hành. Sự linh hoạt và khiêm tốn là tài sản quan trọng nhất khi ở nơi xa lạ.',
    advice: 'Thích nghi với môi trường mới một cách khiêm tốn. Đừng áp đặt cách cũ lên hoàn cảnh mới — học từ những gì xung quanh.',
    energy: 'neutral', keywords: ['hành trình', 'xa lạ', 'thích nghi', 'khiêm tốn'],
  },
  {
    number: 57, symbol: '䷸', nameHan: '巽', nameVi: 'Tốn',
    upperTrigram: 'Tốn', lowerTrigram: 'Tốn',
    meaning: 'Sự thâm nhập nhẹ nhàng nhưng bền vững. Gió không phá vỡ mà len lỏi vào mọi ngóc ngách — ảnh hưởng qua sự kiên nhẫn và nhất quán, không qua sức ép.',
    advice: 'Tác động qua sự kiên nhẫn và nhất quán thay vì áp lực trực tiếp. Sự thuyết phục nhẹ nhàng hiệu quả hơn ép buộc.',
    energy: 'favorable', keywords: ['kiên nhẫn', 'thâm nhập', 'ảnh hưởng', 'nhẹ nhàng'],
  },
  {
    number: 58, symbol: '䷹', nameHan: '兌', nameVi: 'Đoài',
    upperTrigram: 'Đoài', lowerTrigram: 'Đoài',
    meaning: 'Niềm vui và sự hài lòng. Niềm vui được chia sẻ nhân đôi — đây là năng lượng của sự kết nối vui vẻ và chân thật. Hạnh phúc thực sự đến từ bên trong và lan toa ra ngoài.',
    advice: 'Nuôi dưỡng niềm vui và chia sẻ nó. Môi trường vui vẻ và tích cực là điều kiện cho sự sáng tạo và hợp tác.',
    energy: 'favorable', keywords: ['niềm vui', 'hài lòng', 'chia sẻ', 'hạnh phúc'],
  },
  {
    number: 59, symbol: '䷺', nameHan: '渙', nameVi: 'Hoán',
    upperTrigram: 'Tốn', lowerTrigram: 'Khảm',
    meaning: 'Tan rã và phân tán. Như gió thổi trên mặt nước — những khối cứng nhắc đang tan chảy. Đây có thể là sự giải phóng khỏi những ràng buộc lỗi thời.',
    advice: 'Hãy để những điều cứng nhắc và lỗi thời tan rã. Sau sự tan rã thường đến sự tái tổ chức tốt hơn.',
    energy: 'neutral', keywords: ['tan rã', 'giải phóng', 'linh hoạt', 'tái tổ chức'],
  },
  {
    number: 60, symbol: '䷻', nameHan: '節', nameVi: 'Tiết',
    upperTrigram: 'Khảm', lowerTrigram: 'Đoài',
    meaning: 'Giới hạn và kỷ luật. Như đập nước kiểm soát dòng chảy — ranh giới rõ ràng tạo ra sức mạnh và trật tự. Không phải mọi hạn chế đều là bất lợi.',
    advice: 'Đặt ra giới hạn rõ ràng cho bản thân và mối quan hệ. Kỷ luật tự giác là nền tảng của tự do thực sự.',
    energy: 'neutral', keywords: ['giới hạn', 'kỷ luật', 'kiểm soát', 'trật tự'],
  },
  {
    number: 61, symbol: '䷼', nameHan: '中孚', nameVi: 'Trung Phu',
    upperTrigram: 'Tốn', lowerTrigram: 'Đoài',
    meaning: 'Sự thành thật và tin tưởng từ bên trong. Không phải vì bị ép mà vì tự mình muốn — sự chân thật nội tâm có sức mạnh thuyết phục lớn hơn bất kỳ lập luận nào.',
    advice: 'Hành động theo lương tâm thực sự, không phải theo kỳ vọng của người khác. Sự thành thật chân thật tạo niềm tin lâu dài.',
    energy: 'favorable', keywords: ['thành thật', 'tin tưởng', 'lương tâm', 'chân thật'],
  },
  {
    number: 62, symbol: '䷽', nameHan: '小過', nameVi: 'Tiểu Quá',
    upperTrigram: 'Chấn', lowerTrigram: 'Cấn',
    meaning: 'Vượt quá một chút trong những việc nhỏ. Đây không phải lúc hành động lớn — mà là lúc chú ý đến các chi tiết nhỏ và điều chỉnh từng bước. Thận trọng trong những thứ nhỏ để tránh sai lầm lớn.',
    advice: 'Tập trung vào những điều chỉnh nhỏ thay vì thay đổi lớn. Đôi khi ít hơn là nhiều hơn.',
    energy: 'neutral', keywords: ['chi tiết', 'thận trọng', 'điều chỉnh', 'nhỏ bé'],
  },
  {
    number: 63, symbol: '䷾', nameHan: '既濟', nameVi: 'Ký Tế',
    upperTrigram: 'Khảm', lowerTrigram: 'Ly',
    meaning: 'Sau khi hoàn thành. Mọi thứ đã vào đúng vị trí — thành công đã đạt được. Nhưng đây cũng là thời điểm dễ mất cảnh giác nhất. Duy trì kết quả khó hơn đạt được chúng.',
    advice: 'Đừng buông thả sau khi đạt thành công. Duy trì kỷ luật và cảnh giác — kết quả tốt cần được bảo vệ.',
    energy: 'neutral', keywords: ['hoàn thành', 'duy trì', 'cảnh giác', 'kỷ luật'],
  },
  {
    number: 64, symbol: '䷿', nameHan: '未濟', nameVi: 'Vị Tế',
    upperTrigram: 'Ly', lowerTrigram: 'Khảm',
    meaning: 'Chưa hoàn thành — và điều đó ổn. Cuộc hành trình vẫn tiếp tục, chưa đến đích. Đây không phải thất bại mà là trạng thái tiếp diễn tự nhiên của cuộc sống.',
    advice: 'Chấp nhận rằng một số thứ chưa sẵn sàng. Đừng ép buộc kết quả trước khi điều kiện chín muồi — hãy tiếp tục hành trình.',
    energy: 'neutral', keywords: ['chưa xong', 'tiếp tục', 'hành trình', 'kiên nhẫn'],
  },
]

export function getHexagram(number: number): Hexagram | undefined {
  return HEXAGRAMS.find(h => h.number === number)
}
